services:
  - type: web
    name: recipe-giver-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000