// // // import type { Metadata } from "next";
// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata: Metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({
// // //   children,
// // // }: Readonly<{
// // //   children: React.ReactNode;
// // // }>) {
// // //   return (
// // //     <html lang="en">
// // //       <body
// // //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// // //       >
// // //         {children}
// // //       </body>
// // //     </html>
// // //   );
// // // }
// // import './globals.css';
// // import Link from 'next/link';

// // export const metadata = {
// //   title: 'NutriChef Chatbot',
// //   description: 'Smart diet and recipe assistant',
// // };

// // export default function RootLayout({ children }: { children: React.ReactNode }) {
// //   return (
// //     <html lang="en">
// //       <body className="bg-gray-50">
// //         <nav className="bg-white shadow p-4 flex justify-between">
// //           <h1 className="text-xl font-bold text-green-600">NutriChef</h1>
// //           <div className="space-x-4">
// //             <Link href="/" className="text-gray-700 hover:text-green-600">Home</Link>
// //             <Link href="/chat" className="text-gray-700 hover:text-green-600">Chat</Link>
// //             <Link href="/login" className="text-gray-700 hover:text-green-600">Login</Link>
// //           </div>
// //         </nav>
// //         <main className="p-4">{children}</main>
// //       </body>
// //     </html>
// //   );
// // }
// // import './globals.css';
// // import Link from 'next/link';
// // import Image from 'next/image';

// // export const metadata = {
// //   title: 'NutriChef Chatbot',
// //   description: 'Smart diet and recipe assistant',
// // };

// // export default function RootLayout({ children }: { children: React.ReactNode }) {
// //   return (
// //     <html lang="en">
// //       <body className="bg-gray-50">
// //         {/* Navbar */}
// //         <nav className="bg-white shadow-md px-6 py-4 flex justify-between items-center">
// //           {/* Logo + Title */}
// //           <div className="flex items-center space-x-2">
// //             <Image
// //               src="https://img.icons8.com/fluency/48/chef-hat.png"
// //               alt="Chef Icon"
// //               width={36}
// //               height={36}
// //             />
// //             <h1 className="text-2xl font-bold text-green-600">NutriChef</h1>
// //           </div>

// //           {/* Navigation Buttons */}
// //           <div className="flex space-x-3">
// //             <Link href="/" className="px-4 py-2 bg-green-500 text-white rounded-lg text-sm hover:bg-green-600 transition">
// //               Home
// //             </Link>
// //             <Link href="/chat" className="px-4 py-2 bg-green-500 text-white rounded-lg text-sm hover:bg-green-600 transition">
// //               Chat
// //             </Link>
// //             <Link href="/login" className="px-4 py-2 bg-green-500 text-white rounded-lg text-sm hover:bg-green-600 transition">
// //               Login
// //             </Link>
// //           </div>
// //         </nav>

// //         {/* Page Content */}
// //         <main className="p-6">{children}</main>
// //       </body>
// //     </html>
// //   );
// // }
// import './globals.css';
// import Link from 'next/link';
// import Image from 'next/image';

// export const metadata = {
//   title: 'NutriChef Chatbot',
//   description: 'Smart diet and recipe assistant',
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-50">
//         {/* Navbar */}
//         <nav className="bg-white shadow-md px-6 py-4 flex justify-between items-center">
//           {/* Logo + Title */}
//           <div className="flex items-center space-x-2">
//             <Image
//               src="https://img.icons8.com/fluency/48/chef-hat.png"
//               alt="Chef Icon"
//               width={36}
//               height={36}
//               priority
//             />
//             <h1 className="text-2xl font-bold text-green-600">NutriChef</h1>
//           </div>

//           {/* Navigation Buttons */}
//           <div className="flex space-x-3">
//             <Link href="/" passHref>
//               <button className="px-4 py-2 bg-green-500 text-white rounded-lg text-sm hover:bg-green-600 transition">
//                 Home
//               </button>
//             </Link>
//             <Link href="/chat" passHref>
//               <button className="px-4 py-2 bg-green-500 text-white rounded-lg text-sm hover:bg-green-600 transition">
//                 Chat
//               </button>
//             </Link>
//             <Link href="/login" passHref>
//               <button className="px-4 py-2 bg-green-500 text-white rounded-lg text-sm hover:bg-green-600 transition">
//                 Login
//               </button>
//             </Link>
//           </div>
//         </nav>

//         {/* Page Content */}
//         <main className="p-6">{children}</main>
//       </body>
//     </html>
//   );
// }
import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'NutriChef Chatbot',
  description: 'Smart diet and recipe assistant',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <Navbar />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
