// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'NutriChef Chatbot',
  description: 'Smart diet and recipe assistant',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <nav className="bg-white shadow p-4 flex justify-between">
          <h1 className="text-xl font-bold text-green-600">NutriChef</h1>
          <div className="space-x-4">
            <Link href="/" className="text-gray-700 hover:text-green-600">Home</Link>
            <Link href="/chat" className="text-gray-700 hover:text-green-600">Chat</Link>
            <Link href="/login" className="text-gray-700 hover:text-green-600">Login</Link>
          </div>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
